name: Assign Author

on:
  workflow_call:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: lluchkaa/actions/assign-author@main
