name: Auto Assign PR Author

on:
  workflow_call:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign-author-of-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: lluchkaa/actions/auto-assign-pr@main
